# Generated by Django 5.2.2 on 2025-06-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='index/')),
                ('video_title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Index',
                'ordering': ['title'],
            },
        ),
    ]
