# Generated by Django 5.2.2 on 2025-06-18 07:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vehicle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
