# Generated by Django 5.2.2 on 2025-06-18 07:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_aboutus_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesoffered',
            name='services_offered_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
