# Generated by Django 5.2.2 on 2025-06-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/images/')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app.servicesoffered')),
            ],
        ),
    ]
