# Generated by Django 5.2.2 on 2025-06-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_aboutus_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_experienced', models.PositiveIntegerField(default=0)),
                ('total_cars', models.PositiveIntegerField(default=0)),
                ('happy_customers', models.PositiveIntegerField(default=0)),
                ('total_branches', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Counter',
                'verbose_name_plural': 'Counter',
            },
        ),
    ]
