# Generated by Django 5.2.2 on 2025-06-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='services/')),
                ('second_image', models.ImageField(upload_to='services/')),
                ('services_offered', models.CharField(max_length=100)),
            ],
        ),
    ]
