# Generated by Django 5.2.2 on 2025-06-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_servicessection'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessection',
            name='services_offered_desc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
