# Generated by Django 5.2.2 on 2025-06-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_servicessection_services_offered_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_offered', models.CharField(max_length=100)),
                ('services_offered_desc', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicessection',
            name='services_offered',
        ),
        migrations.RemoveField(
            model_name='servicessection',
            name='services_offered_desc',
        ),
    ]
