# Generated by Django 5.2.2 on 2025-06-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprequest',
            name='created_at',
        ),
        migrations.AddField(
            model_name='triprequest',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='phone',
            field=models.CharField(default='9800000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='dropoff_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='pickup_location',
            field=models.CharField(max_length=100),
        ),
    ]
