# Generated by Django 5.2.2 on 2025-06-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_triprequest_created_at_triprequest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
