# Generated by Django 5.2.2 on 2025-06-16 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_carrentalrequest_vehicleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=50, null=True)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('luggage_capacity', models.PositiveIntegerField(blank=True, help_text='Luggage capacity in liters', null=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='app.carrentalrequest')),
            ],
        ),
    ]
