# Generated by Django 5.2.2 on 2025-06-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_carspec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesoffered',
            name='services_offered',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
