# Generated by Django 5.2.2 on 2025-06-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_contactdetail_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
